version: '3.3'
volumes:
  media_food:
  static_food:
  pg_data_food:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_food:/var/lib/postgresql/data

  backend:
    image: elvaleron/foodgram_backend
    env_file:
      - .env
    volumes:
      - static_food:/backend_static
      - media_food:/media
    depends_on:
      - db

  frontend:
    image: elvaleron/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_food:/frontend_static

  gateway:
    image: elvaleron/foodgram_gateway
    ports:
      - "80:80"
    volumes:
      - static_food:/staticfiles/
      - media_food:/mediafiles/
    depends_on:
      - backend
      - frontend

