version: '3.3'
volumes:
  media_food:
  static_food:
  pg_data_food:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_food:/var/lib/postgresql/data

  backend:
    image: elvaleron/foodgram_backend
    env_file:
      - .env
    volumes:
      - static_food:/app/static
      - media_food:/app/media
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: elvaleron/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: elvaleron/foodgram_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_food:/staticfiles/static/
      - media_food:/mediafiles/media/
    depends_on:
      - backend
      - frontend